### ISSUE TITLE
Timeout when running

### ISSUE THREAD

**Issue by ghost** [countercept/doublepulsar-detection-script#12]
So I did see the other Issue about a timeout, I get a different message however.

I'm on a german Windows 10 so I will translate the error message by myself, I included the screenshot anyway.

![image](https://cloud.githubusercontent.com/assets/25876791/25436062/64372dbe-2a92-11e7-8b67-249c80683d02.png) (censored my IP)

"socket.error: [Errno 10060] An attempt to connect failed because the opposite didn't react after a certain period of time or the opened connection was faulty because the connected host didn't react"

Did I do something wrong? My internet is working, obviously.

Thanks

**Comment by countercept** [comment]
Both of those errors are happening at the TCP level. That likelihood here is that either TCP port 445/3389 were not listening on the target IP or a firewall was preventing access to them. 

The script can only check systems that have the SMB and RDP services listening and accessible from the system being used to test them.
