### ISSUE TITLE
INFECTED?

### ISSUE THREAD

**Issue by slowmotion425** [countercept/doublepulsar-detection-script#13]
what need i do?

abload.de/img/cmdgss15.png

**Comment by CHEF-KOCH** [comment]
You could block the ports 445 and 3389 (if you not need them) or shut down their services.

**Comment by countercept** [comment]
I can't read German but that looks like in the first case the port was probably inaccessible and in the second case it did not make it all the way through the protocol exchange and so should not be infected.
