### ISSUE TITLE
Validate finding by communicating with the host

### ISSUE THREAD

**Issue by Viss** [countercept/doublepulsar-detection-script#2]
So while the script finds hosts there have been several discussions on twitter regarding the authenticity of the findings. The easiest way to put these to bed is to actually utilize the ping functionality to do what it is designed to do, and to obtain some details about the host - which simply couldn't be done if the finding was a one-byte-false-positive.

The commandline version of the backdoor produces some fairly verbose output, and if this script could be modified to produce this same output, there would be zero question about false positives.

![image](https://cloud.githubusercontent.com/assets/1756255/25308724/185761cc-2770-11e7-9cf7-b7695ad82207.png)

**Comment by mrfbos** [comment]
I keep getting the following error messages when running detect_doublepulsar_rdp.py:

[ERROR] [192.168.14.138] - [Errno 110] Connection timed out
[ERROR] [192.168.14.11] - [Errno 111] Connection refused

I also get the following errors when running detect_doublepulsar_smb.py:

Traceback (most recent call last):
  File "detect_doublepulsar_smb.py", line 124, in <module>
    check_ip(ip)
  File "detect_doublepulsar_smb.py", line 50, in check_ip
    s.connect((host, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 110] Connection timed out


Any Help ?

**Comment by countercept** [comment]
I think the OS details come from earlier packets and so probably aren't a more reliable indicator or infection but @_FireFart_ added an awesome pull request to add the XOR key details in that do come from the ping response and so I've merged that in.
